---
certbot:
  email: ken@kenmoini.com
  certificates:
    - name: kemo.network
      extra_sans:
      - www.kemo.network
    - name: lab.kemo.network
    - name: cloud.kemo.network
    - name: tower.kemo.network
    #- name: no.kemo.labs

haproxy:

  dns_resolver: 192.168.42.9:53
  lb_vip: 192.168.42.28

  acls:
  - name: path_aisvcapi
    type: path_beg
    value: /api/

  frontend_https:
    use_backends:
    - name: assistedserviceui
      acl: host_assistedservice

  servers:
  - name: nextcloud
    backend_target: 192.168.42.25:80
    uri: cloud.kemo.network
    extra_backend_config:
      - acl url_discovery path /.well-known/caldav /.well-known/carddav
      - http-request redirect location /remote.php/dav/ code 301 if url_discovery

  - name: tower
    backend_target: 192.168.42.41:443
    extra_backend_server_args: ssl verify none
    extra_backend_options:
      - http-server-close
    uri: tower.kemo.network

  - name: bazarr
    backend_target: 192.168.42.20:6767
    uri: bazarr.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: sonarr
    backend_target: 192.168.42.20:8989
    uri: sonarr.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: radarr
    backend_target: 192.168.42.20:7878
    uri: radarr.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: jackett
    backend_target: 192.168.42.20:9117
    uri: jackett.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: deluge
    backend_target: 192.168.42.24:8112
    uri: deluge-web.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: nexus
    backend_target: 192.168.42.22:8081
    uri: nexus.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: grafana
    backend_target: 192.168.42.27:3000
    uri: grafana.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: prometheus
    backend_target: 192.168.42.27:9090
    uri: prometheus.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: alertmanager
    backend_target: 192.168.42.27:9093
    uri: alertmanager.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: keycloak
    backend_target: 192.168.42.18:8080
    uri: sso.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: dashy
    backend_target: 192.168.42.32:80
    uri: dashy.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: wwwwebsvcs
    backend_target: 192.168.42.29:80
    uri: kemo.labs
    cert_name: wildcard.kemo.labs

  - name: websvcs
    backend_target: 192.168.42.29:80
    uri: kemo.labs
    cert_name: wildcard.kemo.labs

  - name: aiimgsvc
    backend_target: 192.168.42.70:8888
    uri: assisted-image-service.kemo.labs
    cert_name: wildcard.kemo.labs

  - name: assistedservice
    backend_target: 192.168.42.70:8090
    uri: assisted-service.kemo.labs
    extra_use_condition: path_aisvcapi
    cert_name: wildcard.kemo.labs

  - name: assistedserviceui
    backend_target: 192.168.42.70:8080
    uri: assisted-service.kemo.labs
    skip_crt_list: true
